COT/urls.py
from django.contrib import admin
from django.urls import path
from datalist.generate_QR_code_service import create_QR_from_item_id
from datalist.views import user_login, user_logout, datalist, search, create_item, success_page, \
    change_item, export_excel, upload_file

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin', admin.site.urls),
    path('login', user_login, name='login'),
    path('logout', user_logout, name='logout'),
    path('', datalist),
    path('itemQRCode', create_QR_from_item_id),
    path('search', search, name='search'),
    path('create_item/', create_item, name='create_item'),
    path('change_item/<int:item_id>/', change_item, name='change_item'),
    path('success', success_page, name='success_page'),
    path('export/excel/', export_excel, name='export_excel'),
    path('upload/', upload_file, name='upload_page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

datalist/models.py
from django.utils import timezone, formats

from auditlog.registry import auditlog
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models

class AdministrativeDocument(models.Model):
    technical = models.ForeignKey('Technical', related_name='docs', on_delete=models.CASCADE)
    document = models.FileField(upload_to='docs/')

class Technical(models.Model):
    CATEGORY = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
    )

    STATUS_CHOICES = (
        ('Встановіть статус', 'Встановіть статус'),
        ('Введено в експлуатацію', 'Введено в експлуатацію'),
        ('На складі', 'На складі'),
    )

    UNIT_MEASUREMENT_CHOICES = (
        ('шт.', 'шт.'),
        ('к-т.', 'к-т.'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    product_name = models.CharField(max_length=100)
    factory_number = models.CharField(max_length=50, null=True, blank=True, default='---')
    inv_number = models.CharField(max_length=50, null=True, blank=True, default='---')
    quantity = models.IntegerField()
    unit_measurement = models.CharField(max_length=20, choices=UNIT_MEASUREMENT_CHOICES, default='шт.')
    price = models.DecimalField(max_digits=12, decimal_places=2)
    storage_location = models.CharField(max_length=100)
    responsible_person = models.CharField(max_length=50, null=True, default='---')
    fixed_person = models.CharField(max_length=50, null=True, default='---')
    item_passport_number = models.CharField(max_length=50, null=True, blank=True, default='---')
    date_of_start = models.DateField(null=True, blank=True, default=timezone.now)
    term_of_use = models.IntegerField()
    term_of_use_document = models.CharField(max_length=100, default='---')
    category = models.CharField(max_length=20, choices=CATEGORY, default='---')
    status = models.CharField(max_length=25, choices=STATUS_CHOICES, default='---')
    terms = models.CharField(max_length=200, blank=True, default='---')
    image = models.ImageField(upload_to='image/', null=True, blank=True)

    def formatted_date_of_start(self):
        if self.date_of_start:
            return self.date_of_start.strftime('%d.%m.%Y')
        return ""

    def formatted_price(self):
        if self.price:
            formatted_price = '{:,.2f}'.format(self.price).replace(',', ' ').replace('.', ',')
            return formatted_price
        return ""

auditlog.register(Technical)
auditlog.register(AdministrativeDocument)

datalist/forms.py
from django import forms
from .models import Technical, AdministrativeDocument

class UploadFileForm(forms.Form):
    file = forms.FileField()

class TechnicalForm(forms.ModelForm):
    class Meta:
        model = Technical
        fields = [
            'product_name',
            'factory_number',
            'inv_number',
            'quantity',
            'unit_measurement',
            'price',
            'storage_location',
            'responsible_person',
            'fixed_person',
            'item_passport_number',
            'date_of_start',
            'term_of_use',
            'term_of_use_document',
            'category',
            'status',
            'terms',
            'image',
        ]

        labels = {
            'product_name': 'Найменування  об’єкта(ів)',
            'factory_number': 'Зав. №',
            'inv_number': 'Інв. (номенклатур.) №',
            'quantity': 'К-сть.',
            'unit_measurement': 'Од. виміру',
            'price': 'Первісна вартість (сума)',
            'storage_location': 'Місцезнаходження об’єкта(ів)',
            'responsible_person': 'МВО (Метеріально відповідальна особа)',
            'fixed_person': 'Закріплено за (особа)',
            'item_passport_number': '№ формуляра (паспорта)' ,
            'date_of_start': 'Дата початку експлуатації',
            'term_of_use': 'Встановлений строк служби об’єкта(ів) в роках',
            'term_of_use_document': 'Керівний документ по строкам служби об’єкта(ів)',
            'category': 'Категорія  об’єкта(ів)',
            'status': 'Статус  об’єкта(ів)',
            'terms': 'Примітка',
            'image': 'Світлина',
        }

        widgets = {
            'date_of_start': forms.DateInput(attrs={'type': 'date'}),
        }

class AdministrativeDocumentForm(forms.ModelForm):
    class Meta:
        model = AdministrativeDocument
        fields = ['document']

        labels = {
            'document': 'Документ',
        }
    def clean_document(self):
        document = self.cleaned_data.get('document')
        max_size = 20 * 1024 * 1024  # 20MB limit
        if document and document.size > max_size:
            raise forms.ValidationError("File size should not exceed 5MB.")
        return document

TechnicalFormSet = forms.inlineformset_factory(
    Technical,
    AdministrativeDocument,
    form=AdministrativeDocumentForm,
    extra=3,  # Number of extra forms (adjust as needed)
    can_delete=True,
)

datalist/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import get_object_or_404
from datalist.forms import TechnicalForm, TechnicalFormSet
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Q
import io
from django.shortcuts import render, redirect
from django.contrib import messages
import pandas as pd
from .filters import TechnicalFilter
from .models import Technical, User
from django.utils.timezone import now
from .forms import UploadFileForm


def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/')  # Replace 'home' with your app's home URL
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def user_logout(request):
    logout(request)
    return redirect('login')


@login_required
def datalist(request):
    all_data = Technical.objects.prefetch_related('docs').order_by('id').all()

    # Apply filters
    filterset = TechnicalFilter(request.GET, queryset=all_data)

    return render(request, 'datalist.html', {
        'filter': filterset,
        'data': filterset.qs,
        'params': request.GET.urlencode()
    })

@login_required
def search(request):
    query = request.GET.get('q')  # Get the search query from the request
    all_data = Technical.objects.all()  # Get all data first

    # Apply search filtering
    if query:
        all_data = all_data.filter(
            Q(user__username__icontains=query) |
            Q(product_name__icontains=query) |
            Q(inv_number__icontains=query) |
            Q(factory_number__icontains=query) |
            Q(quantity__icontains=query) |
            Q(unit_measurement__icontains=query) |
            Q(price__icontains=query) |
            Q(storage_location__icontains=query) |
            Q(responsible_person__icontains=query) |
            Q(fixed_person__icontains=query) |
            Q(date_of_start__icontains=query) |
            Q(item_passport_number__icontains=query) |
            Q(term_of_use__icontains=query) |
            Q(term_of_use_document__icontains=query) |
            Q(status__icontains=query) |
            Q(terms__icontains=query)
        )

    # Apply additional filters
    filterset = TechnicalFilter(request.GET, queryset=all_data)

    return render(request, 'search.html', {
        'results': filterset.qs,  # Apply both search and filters
        'query': query,
        'filter': filterset  # Pass the filter form to the template
    })

@login_required
def create_item(request):
    if request.method == 'POST':
        technical_form = TechnicalForm(request.POST, request.FILES)
        formset = TechnicalFormSet(request.POST, request.FILES)

        if technical_form.is_valid() and formset.is_valid():
            technical_instance = technical_form.save(commit=False)
            technical_instance.user = request.user
            technical_instance.save()

            instances = formset.save(commit=False)
            for instance in instances:
                instance.technical = technical_instance
                instance.save()

            return redirect('success_page')

    else:
        technical_form = TechnicalForm()
        formset = TechnicalFormSet()

    return render(request, 'create_item.html', {
        'technical_form': technical_form,
        'formset': formset,
    })

@login_required
def change_item(request, item_id):
    item = get_object_or_404(Technical, pk=item_id)

    if request.method == 'POST':
        technical_form = TechnicalForm(request.POST, request.FILES, instance=item)
        formset = TechnicalFormSet(request.POST, request.FILES, instance=item)

        if technical_form.is_valid() and formset.is_valid():
            technical_form.instance.user = request.user
            technical_form.save()
            formset.save()
            return redirect(reverse('success_page'))

    else:
        technical_form = TechnicalForm(instance=item)
        formset = TechnicalFormSet(instance=item)

    return render(request, 'change_item.html', {
        'technical_form': technical_form,
        'formset': formset
    })

@login_required
def success_page(request):
    return render(request, 'success.html')


@login_required
def export_excel(request):
    query = request.GET.get('q', '')

    # Retrieve filter parameters from the request
    all_data = Technical.objects.prefetch_related('docs').order_by('id').all()

    filterset = TechnicalFilter(request.GET, queryset=all_data)
    filtered_data = filterset.qs  # Apply filters

    # Define required fields
    required_fields = [
        'user__username',
        'product_name',
        'factory_number',
        'inv_number',
        'quantity',
        'unit_measurement',
        'price',
        'storage_location',
        'responsible_person',
        'fixed_person',
        'item_passport_number',
        'date_of_start',
        'term_of_use',
        'term_of_use_document',
        'category',
        'status',
        'terms'
    ]

    # Apply search filters if a query is present
    if query:
        technical_objects = Technical.objects.filter(
            Q(user__username__icontains=query) |
            Q(product_name__icontains=query) |
            Q(inv_number__icontains=query) |
            Q(factory_number__icontains=query) |
            Q(quantity__icontains=query) |
            Q(unit_measurement__icontains=query) |
            Q(price__icontains=query) |
            Q(storage_location__icontains=query) |
            Q(responsible_person__icontains=query) |
            Q(fixed_person__icontains=query) |
            Q(date_of_start__icontains=query) |
            Q(item_passport_number__icontains=query) |
            Q(term_of_use__icontains=query) |
            Q(term_of_use_document__icontains=query) |
            Q(status__icontains=query) |
            Q(terms__icontains=query)
        ).values(*required_fields)
    else:
        technical_objects = filtered_data.values(*required_fields)

    # Convert to DataFrame
    df = pd.DataFrame(list(technical_objects))

    # Create an in-memory output file
    output = io.BytesIO()

    # Write DataFrame to an Excel file
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Technical Data')

    # Set response parameters
    response = HttpResponse(
        output.getvalue(),
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )
    response['Content-Disposition'] = 'attachment; filename="technical_data.xlsx"'

    return response


def import_excel_to_postgresql(file):
    """Function to process the uploaded Excel file and save data to PostgreSQL"""
    df = pd.read_excel(file, engine='openpyxl')
    duplicate_messages = []  # List to store duplicate messages

    for _, row in df.iterrows():
        try:
            username = str(row.get('user__username', '')).strip()  # Using 'user' instead of 'username'

            user = User.objects.get(username=username)  # Find user by username

            factory_number = row.get('factory_number', '---')
            inv_number = row.get('inv_number', '---')

            # Check for existing records with the same factory_number or inv_number
            if Technical.objects.filter(factory_number=factory_number).exists() or \
               Technical.objects.filter(inv_number=inv_number).exists():
                message = f"Пропускання повторного запису для Заводський №: {factory_number}, Інв. (номенклатур.) №: {inv_number}"
                duplicate_messages.append(message)
                continue  # Skip this record

            technical = Technical(
                user=user,
                product_name=row['product_name'],
                factory_number=row.get('factory_number', '---'),
                inv_number=row.get('inv_number', '---'),
                quantity=int(row['quantity']),
                unit_measurement=row.get('unit_measurement', 'шт.'),
                price=float(row['price']),
                storage_location=row['storage_location'],
                responsible_person=row.get('responsible_person', '---'),
                fixed_person=row.get('fixed_person', '---'),
                item_passport_number=row.get('item_passport_number', '---'),
                date_of_start=pd.to_datetime(row['date_of_start'], errors='coerce').date() if pd.notna(row['date_of_start']) else now().date(),
                term_of_use=int(row['term_of_use']),
                term_of_use_document=row.get('term_of_use_document', '---'),
                category=row.get('category', '---'),
                status=row.get('status', '---'),
                terms=row.get('terms', '---')
            )
            technical.save()
        except Exception as e:
            duplicate_messages.append(f"Error importing row {row.to_dict()}: {e}")

    return duplicate_messages  # Return duplicate messages


def upload_file(request):
    """Handles file upload and triggers the import function"""
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['file']
            duplicate_messages = import_excel_to_postgresql(file)  # Get duplicate messages

            if duplicate_messages:
                for msg in duplicate_messages:
                    messages.warning(request, msg)  # Store duplicate messages

            messages.success(request, "Файл успішно імпортовано!")
            return redirect('upload_page')  # Redirect to the upload page

    else:
        form = UploadFileForm()

    return render(request, 'upload.html', {'form': form})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>COT</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>
    <div class="header">
        <div class="header sticky">
            <header>
                <nav>
                    <div class="logo"><a href="/">COT</a></div>
                    <div class="center-container">

                        <!-- Button to toggle dropdown -->
                        <div class="filter-link" id="filterButton">
                            <a onclick="toggleDropdown()"></a>
                        </div>

                        <!-- Dropdown content -->
                        <div class="filter-dropdown-container" id="filterDropdown">
                            <form method="get">
                                <div style="text-align: left; margin-top: 5px;">
                                    <label for="id_category">Категорія обєктів(ів):</label>
                                    {{ filter.form.category }}
                                </div>

                                <div style="text-align: left; margin-top: 5px;">
                                    <label for="id_status">Статус обєктів(ів):</label>
                                    {{ filter.form.status }}
                                </div>

                                <div style="text-align: left; margin-top: 5px;">
                                    <label for="id_storage_location">Місцезнаходження обєктів(ів):</label>
                                    {{ filter.form.storage_location }}
                                </div>

                                <div style="text-align: left; margin-top: 5px;">
                                    <label for="id_responsible_person">МВО:</label>
                                    {{ filter.form.responsible_person }}
                                </div>

                                <div style="text-align: left; margin-top: 5px;">
                                    <label for="id_fixed_person">Закріплено за (особа):</label>
                                    {{ filter.form.fixed_person }}
                                </div>

                                <div style="text-align: left; margin-top: 5px;">
                                    <label for="id_price">Первісна вартість (сума):</label>
                                    {{ filter.form.price }}
                                </div>

                                <div style="text-align: right; margin-top: 10px;">
                                    <button type="submit">Фільтрувати</button>
                                </div>

                            </form>
                        </div>


                        <form method="GET" action="{% url 'search' %}">
                            <input type="search" type="text" name="q" placeholder="Пошук...">
                            <button type="submit">Знайти</button>
                        </form>

                        <div class="plus-link">
                            <a href="/create_item"></a>
                        </div>

                        <!-- Import Button -->
                        <div class="db-link">
                            <a href="/upload"></a>
                        </div>

                        <!-- Export Button -->
                        <div class="exel-link">
                            <a href="{% url 'export_excel' %}?q={{ query }}&{{ params }}"></a>
                        </div>

                    </div>

                    <ul>

                        <div class="admin-link">
                            <a href="/admin"></a>
                        </div>

                        <div class="logout-link">
                            <a href="logout"></a>
                        </div>

                    </ul>
                </nav>

                <div class="controls">
                    <div id="buttons-container"></div>
                </div>

            </header>
        </div>
    </div>

    <div class="content">
        <content>
            {% block content %}
            {% endblock %}
        </content>
    </div>

    <!--Script for filter button-->
    <script>
        function toggleDropdown() {
            document.getElementById("filterDropdown").classList.toggle("show");
        }
    </script>

    <script>
        // List of pages where the button should be hidden
        const hiddenPages = ["/create_item/", "/upload/", "{% url 'search' %}"];

        // Get the current page path
        const currentPage = window.location.pathname;

        // Check if the current page is in the hidden list
        if (hiddenPages.includes(currentPage)) {
            document.getElementById("filterButton").style.display = "none";
        }
    </script>

</body>
</html>

templates/change_item.html
{% extends 'base.html' %}

{% block content %}
{% if technical_form.instance.user == request.user %}
<item_body>
    <create_item>
        <h2>Змінити запис</h2>

        <!-- Display the current image -->
        {% if technical_form.instance.image %}
            <img src="{{ technical_form.instance.image.url }}" alt="Current Image" width="200">
        {% endif %}

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ technical_form.as_p }}

            <fieldset>
                <legend>Документація (Видат. накладна, Акт_ПП, Акт_ВВЕ, Внут. накладна тощо)</legend>
                {{ formset.management_form }}
                {% for form in formset.forms %}
                    {{ form.as_p }}
                {% endfor %}
            </fieldset>

            <div style="text-align: right; margin-top: 20px;">
                <button type="submit">Зберегти зміни</button>
            </div>

        </form>

    </create_item>
</item_body>
</html>
{% else %}
<item_body>
    <not_available>
        <h1>Зміни доступні тільки для відповідальної особи!</h1>
    </not_available>
</item_body>
{% endif %}
{% endblock %}

templates/create_item.html
{% extends 'base.html' %}

{% block content %}
<item_body>
    <create_item>
        <h2>Створити новий запис</h2>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ technical_form.as_p }}

            <fieldset>
                <legend>Документація (Видат. накладна, Акт_ПП, Акт_ВВЕ, Внут. накладна тощо)</legend>
                {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                    {% endfor %}
            </fieldset>

            <div style="text-align: right; margin-top: 20px;">
                <button type="submit">Зберегти</button>
            </div>

        </form>

    </create_item>
</item_body>
{% endblock %}

templates/login.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>COT</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
    <h1>COT</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</body>
</html>

templates/not_available.html
{% extends 'base.html' %}

{% block content %}
<item_body>
    <not_available>
        <h1>Зміни доступні тільки для відповідальної особи!</h1>
    </not_available>
</item_body>
{% endblock %}

templates/success.html
{% extends 'base.html' %}

{% block content %}
<item_body>
    <success>
        <h1>Успішно!</h1>
    </success>
</item_body>
{% endblock %}

templates/upload.html
{% extends 'base.html' %}

{% block content %}

<item_body>
    <create_item>
        <div class="content">
            <h2>Для імпортування данних з .xlsx переконайтесь що ваш файл відповідає зазначеній структурі та містить необхідні заголовки</h2>

            <table id="dataTable">
                <thead>
                    <tr>
                        <th style="font-size: 13px;">user__username</th>
                        <th style="font-size: 13px;">product_name</th>
                        <th style="font-size: 13px;">factory_number</th>
                        <th style="font-size: 13px;">inv_number</th>
                        <th style="font-size: 13px;">quantity</th>
                        <th style="font-size: 13px;">unit_measurement</th>
                        <th style="font-size: 13px;">price</th>
                        <th style="font-size: 13px;">storage_location</th>
                        <th style="font-size: 13px;">responsible_person</th>
                        <th style="font-size: 13px;">fixed_person</th>
                        <th style="font-size: 13px;">item_passport_number</th>
                        <th style="font-size: 13px;">date_of_start</th>
                        <th style="font-size: 13px;">term_of_use</th>
                        <th style="font-size: 13px;">term_of_use_document</th>
                        <th style="font-size: 13px;">category</th>
                        <th style="font-size: 13px;">status</th>
                        <th style="font-size: 13px;">terms</th>
                    </tr>
                </thead>

                <thead>
                    <tr>
                        <td style="font-size: 13px;">admin</td>
                        <td style="font-size: 13px;">Laptop Dell XPS</td>
                        <td style="font-size: 13px;">DLL12345</td>
                        <td style="font-size: 13px;">111485856</td>
                        <td style="font-size: 13px;">1</td>
                        <td style="font-size: 13px;">к-т.</td>
                        <td style="font-size: 13px;">1500.50</td>
                        <td style="font-size: 13px;">Warehouse A</td>
                        <td style="font-size: 13px;">John Doe</td>
                        <td style="font-size: 13px;">Jane Smith</td>
                        <td style="font-size: 13px;">PASSPORT1234</td>
                        <td style="font-size: 13px;">23.05.2024</td>
                        <td style="font-size: 13px;">3</td>
                        <td style="font-size: 13px;">5</td>
                        <td style="font-size: 13px;">1</td>
                        <td style="font-size: 13px;"></td>
                        <td style="font-size: 13px;"></td>
                    </tr>
                </thead>

                <thead>
                    <tr>
                        <td style="font-size: 13px;">user</td>
                        <td style="font-size: 13px;">product_name</td>
                        <td style="font-size: 13px;">weir3422250</td>
                        <td style="font-size: 13px;">111586954</td>
                        <td style="font-size: 13px;">3</td>
                        <td style="font-size: 13px;">шт.</td>
                        <td style="font-size: 13px;">price</td>
                        <td style="font-size: 13px;">storage_location</td>
                        <td style="font-size: 13px;">responsible_person</td>
                        <td style="font-size: 13px;">fixed_person</td>
                        <td style="font-size: 13px;">item_passport_number</td>
                        <td style="font-size: 13px;">22.02.2025</td>
                        <td style="font-size: 13px;">5</td>
                        <td style="font-size: 13px;">term_of_use_document</td>
                        <td style="font-size: 13px;">1</td>
                        <td style="font-size: 13px;">status</td>
                        <td style="font-size: 13px;">terms</td>
                    </tr>
                </thead>
            </table>

            <div class="import_data">
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}

                <form action="{% url 'upload_page' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="file" name="file" accept=".xlsx">
                    <button type="submit">Імпортувати дані</button>
                </form>
            </div>

        </div>
    </create_item>
</item_body>

{% endblock %}